version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    install:
      - pip install -U pip
      - pip install . --group docs
    pre_build:
      - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ docs/_build/linkcheck
    build:
      html:
        - python -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs/ $READTHEDOCS_OUTPUT/html
